### ISSUE TITLE
Capistrano's repo url

### ISSUE THREAD

**Issue by lazywei** [atmos/heaven#126]
In the document: https://github.com/atmos/heaven/blob/master/doc/providers.md
It says we should use https:// instead of git:// for repo url. However, in such case, git will ask for the username & password, which obviously will break the deployment .. How can I resolve this?

**Comment by atmos** [comment]
You can encode the username and password in the URL or use a credential cacher.

**Comment by lazywei** [comment]
I feel using "username:password@github.com" is somehow anti-pattern... I'd need to write this in my cap's deploy.rb
Any specific reason why not use `git@github.com` protocol? I've tried it, and it works with heaven.

**Comment by atmos** [comment]
That's fine and I use that pattern pretty frequently myself. Using the HTTPS protocol is generally easier since some firewalls and stuff block ssh access.

**Comment by lazywei** [comment]
My thing is, if I use capistrano, then I'd need to write the deployer's github account/password in `deploy.rb` Which means I will check them into git ... I thought check in any sensitive information into git is not OK?

Hmm.. I give it a second thought, maybe we can write the account/password into ENV, and then let the capistrano read the account/password from there?

Thanks!

**Comment by atmos** [comment]
There's also git credential caching where you can run `git ls-remote https://github.com/me/my-repo` and have it store the passwords for future use. Using the environment is probably a good idea, that's where the ssh keys used for cap accessing the remove servers are stored currently.

**Comment by lazywei** [comment]
I try to use credential caching. And now `git ls-remote` works.
However, the `git remote update` seems not working (here is cap's logs):
```
INFO [5f7e3d75] Running /usr/bin/env git remote update as deployer@staging.yoctol.com
 DEBUG [5f7e3d75] Command: cd /Users/deployer/www/guardian/repo && ( PATH=/usr/local/bin:$(/usr/local/bin/npm bin):$PATH RBENV_ROOT=~/.rbenv RBENV_VERSION=2.2.0 GIT_ASKPASS=/bin/echo GIT_SSH=/tmp/guardian/git-ssh.sh /usr/bin/env git remote update )
 DEBUG [5f7e3d75] 	Fetching origin
 DEBUG [5f7e3d75] 	Fetching origin
 DEBUG [5f7e3d75] 	Error reading response length from authentication socket.
```

What does the "error reading ..." mean?
Thanks.

**Comment by atmos** [comment]
I can't find that call in the heaven source code.

```
~/p/heaven(master*)$ ack -r "git remote update"
~/p/heaven(master*)$ 
```

**Comment by lazywei** [comment]
Sorry for not make this clear. This is capistrano's log. So actually this call should reside in capistrano.
I'm just wondering if this has anything to do with my heaven's setting.
Thanks.

**Comment by atmos** [comment]
I don't think so. It depends on the environment that heaven was launched under and it is expected that most of that environment is passed on to other processes. My guess is that somewhere along the chain of invoking processes a shell isn't getting access to the auth socket that's used in the failed ssh exchange.

**Comment by dblandin** [comment]
Isn't this what the `DEPLOYMENT_PRIVATE_KEY` environment variable is for?

We're using `git@github.com:owner/repo.git` urls without a problem. A deploy private key is set as an environment variable. The public key has been added to GitHub and the servers we're deploying to.

**Comment by atmos** [comment]
@dblandin It's easy for them to be different in a lot of contexts. Yeah, though, make it the same is the easy way out.

**Comment by atmos** [comment]
I'm not gonna be working on this project in the foreseeable future.
