### ISSUE TITLE
Update provider libraries to download tarball vs cloning a git repository

### ISSUE THREAD

**Issue by maletor** [atmos/heaven#148]
Downloading the archive vs cloning the repository is a detail of the provider I think it would be nice to configure or change altogether.

In fact, using the archive link may be the better route for all deploys. The reason being is you can download a 3GB git repo as a 25MB tarball a lot faster.

**Comment by atmos** [comment]
One area where this is advantageous to clone is frequently deploying and reusing the same checkout. Perhaps we should try the `--depth` command ` ([link](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#safe=off&q=git+clone+depth+branch))

**Comment by maletor** [comment]
But the same tarball and even the same extracted tarball can be reused just the same.

**Comment by atmos** [comment]
Yup, they will be but small changes between deployments will end up being more costly by checking out new revisions rather than a fetch and hard reset to the specific sha.

Wanna whip up a PR and we can look at it more closely?

**Comment by maletor** [comment]
Right, that's certainly a disadvantage. But, probably not a big one. Let's examine the scenarios.

If you have a small repository anyways then the download time is negligible, about as negligible as a git connection and fetch.

If you have a large repository, then it should be obvious an archive link would be advantageous.

It might look something like this [provider](https://gist.github.com/maletor/bd7f5ea0537ba22c5c7c).

**Comment by atmos** [comment]
The bundler capistrano provider will also have the drawback of rebundling on each new tarball download, often really time/resource expensive, which will slow down your deployments.

**Comment by maletor** [comment]
Again, I don't think there are any extra cpu cycles offered by the tarball approach. 

On heroku everyting in `/tmp` is gone after reboot or dyno cycling which happens once or twice a day. So, the system should work fast in the worse case scenario more often.

That being said, we're looking at exactly the same time for cached git repositories or tarball downloads once git fetch or curl has been run. Once gems are installed, they are simply installed and bundle install runs bundle check and exits very quickly.

**Comment by atmos** [comment]
Can you make a PR for this?

**Comment by maletor** [comment]
Yes. On an extended vacation so give me some time.
