### ISSUE TITLE
Possible to use a different version of Ruby in bundler_capistrano?

### ISSUE THREAD

**Issue by shaneog** [atmos/heaven#153]
I have an application that runs on Ruby 2.2.2 and I have the Ruby version specified in the Gemfile: `ruby '2.2.2'`.

When I try to deploy with _heaven_, I get the message:
```
Your Ruby version is 2.1.2, but your Gemfile specified 2.2.2
```
Is there any way I can deploy a Rails application with a different version of Ruby than _heaven_ itself?

**Comment by atmos** [comment]
I don't think I've ever tried doing that so I'm not entirely sure. I figured the `Bundler.with_clean_env` stuff would handle that but perhaps it doesn't. How are you managing your ruby installs?

**Comment by shaneog** [comment]
On our servers we use [chruby](https://github.com/postmodern/chruby) and we have a `.ruby-version` file in the root of our project directory containing the text `2.2.2`.

I'm running _heaven_ on Heroku, if that helps.

The first few lines of the Gemfile are: 
```ruby
source 'https://rubygems.org'

ruby '2.2.2'

gem 'rails', '4.2.2'
```

**Comment by shaneog** [comment]
It turns out that Heroku uses the Ruby version from the application Gemfile (i.e. _heaven_) and doesn't seem to support changing the Ruby version for other commands. 
I'm still looking into the possibilty of doing this programmatically but currently I'm not getting anywhere.
