### ISSUE TITLE
Cannot Deploy to Heroku using web UI

### ISSUE THREAD

**Issue by johnnybridges** [atmos/heaven#155]
Clicked on the 'Deploy to Heroku' button, entered all the required config variables. All was going well and then boom. Heroku isn't happy - it won't complete deployment when using the web interface. 

Seems weird/overkill that a deprecation warning stops it from finishing - is there a way around this?

See screenshot here - http://files.artificial.io/image/3K1Q3x1g3T0G

Full message from the 'Run scripts & scale dynos' section below:
```
DEPRECATION WARNING: The configuration option `config.serve_static_assets` has been renamed to `config.serve_static_files` to clarify its role (it merely enables serving everything in the `public` folder and is unrelated to the asset pipeline). The `serve_static_assets` alias will be removed in Rails 5.0. Please migrate your configuration files accordingly. (called from block in tsort_each at /app/vendor/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226)
Migrating to CreateDeployments (20140329200427)
== 20140329200427 CreateDeployments: migrating ================================
-- create_table(:deployments)
   -> 0.0213s
== 20140329200427 CreateDeployments: migrated (0.0214s) =======================

Migrating to CreateRepositories (20140728040201)
== 20140728040201 CreateRepositories: migrating ===============================
-- create_table(:repositories)
   -> 0.0203s
-- add_column(:deployments, :repository_id, :integer)
   -> 0.0023s
== 20140728040201 CreateRepositories: migrated (0.0354s) ======================
```

Full build log can be seen here https://gist.github.com/johnnybridges/365ec66a353deb3105e8

Thanks!

**Comment by atmos** [comment]
It's just a warning that I removed. The part that says

```
-----> Launching... done, v7
```

in your heroku output means that it deployed.  You probably have an application error, check the logs.

**Comment by johnnybridges** [comment]
Thanks for the quick reply! I can't check the logs though because when the warning is shown at the `Run scripts & scale dynos` stage, Heroku then deletes the environment - so can't actually check. Don't think I'm the only one either - http://stackoverflow.com/questions/31127976/deployment-to-heroku-of-heaven-fail
