### ISSUE TITLE
Why DEPLOYMENT_PRIVATE_KEY don't take effect?

### ISSUE THREAD

**Issue by cloudy9101** [atmos/heaven#156]
heaven on the heroku, my repo was deploied on the server use capistrano.
When heaven go to login to the server, it need password.   
The report gist is [here](https://gist.github.com/cloudy9101/2273929b7a3548bf8f07).

I put the pub key to the server's authorize_keys file, and 
  `heroku config:set DEPLOYMENT_PRIVATE_KEY=my private key`
but it still need the password, is there any ideas? Thx.

**Comment by atmos** [comment]
When you look at the environmental variable is it all on one line? You may be able to debug it by running `ssh -vv user@hostname` in a heroku console. You can get a console with `heroku run bash` inside of your heaven app.

**Comment by cloudy9101** [comment]
Thanks a lot. My mistake, I copy the ssh private key without BEGIN and END lines, all going well now.
