### ISSUE TITLE
Heroku deploy button not working

### ISSUE THREAD

**Issue by bilby91** [atmos/heaven#163]
I tried several times to deploy the app in heroku but I never could finish the process. 

Is there any special stuff to do ?

**Comment by atmos** [comment]
I need to take a closer look because they've changed a bunch of the underlying implementation since they launched.

**Comment by bilby91** [comment]
@atmos Are you running heaven on heroku now ?

**Comment by atmos** [comment]
I am, I just haven't used the button in a while. I recently started working at heroku so I'll try to get one spun up now that I don't have to worry about paid accounts. It's a long story.. :smiley:

**Comment by bilby91** [comment]
Awesome! How is heroku treating you ? Nice place to work ?
