### ISSUE TITLE
404 error page on "/resque" (after OAuth'ing with GitHub)

### ISSUE THREAD

**Issue by willdurand** [atmos/heaven#165]
Hi!

I have installed heaven on Heroku, and successfully deployed my app using `hubot-deploy`, and so on. Everything seems to work fine under the hood, however when I first browsed heaven, I got an error telling me that the page did not exist:

![screen shot 2015-08-17 at 17 49 52](https://cloud.githubusercontent.com/assets/217628/9309260/b9ebb8ae-4508-11e5-8721-02d757fc4fd5.png)

Heroku logs say the route does not match anything:

```
ActionController::RoutingError (No route matches [GET] "/resque"):
[...]
```

Any hints on what happened? I still can't access anything at this URI. Is there any "web view" on heaven?

Thank you!
William

**Comment by willdurand** [comment]
Reinstalling the app solved the issue. Can't explain what happened to be honest..

**Comment by atmos** [comment]
I've run into that where migrations didn't run and the app wouldn't start, so you'd get an error page like that. Glad you figured it out.

**Comment by willdurand** [comment]
Ah thanks for your input!
