### ISSUE TITLE
Archive downloads break deployments

### ISSUE THREAD

**Issue by Mumakil** [atmos/heaven#175]
It seems that having heaven download archives instead of cloning the repo when using `bundler_capistrano` provider completely broke more than half of our service's deployments. This is partly due to some projects doing things with git submodules or older cap 2 trying to look up the head commit locally. 

This change breaks so many things, that I'd like to have it be configurable so we can at least somehow have a way to make everything compatible again without having to have entire deployment infrastructure down while tracking down and fixing unknown things that are caused by not being in a git repo. Capistrano also behaves slightly differently if you give it sha's (like autodeploy does) or branches so the breakages can be subtle.

**Comment by atmos** [comment]
Oof, sorry. Can you make a pr to revert it and/or verify that it's doing ok? This is the unfortunate downside of having providers I don't use. :disappointed:

**Comment by Mumakil** [comment]
Sure, I'll cook up a pr on monday.
