### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by khirakawa** [atmos/heaven#176]
Had some questions regarding documentation:

- Is the correct webhook for heaven `http://<url_for_heave>/events`? I read the documentation a number of times, but could not find this information. 

- I noticed that heaven uses the `postgresql` plugin, but in `config/database.yml`, sqlite3 is used instead.  Where is `postgresql` used?  Is it still needed?

- What should the OAuth authorization callback URL be for generating a client id and secret?

**Comment by cyc** [comment]
@atmos 

>I noticed that heaven uses the postgresql plugin, but in config/database.yml, sqlite3 is used instead. Where is postgresql used? Is it still needed?

+1 on this, pretty confusing. I actually get a `ERROR -- : FATAL:  database "db/development.sqlite3" does not exist` error when starting up the app, despite passing in a `DATABASE_URL` environment variable

>What should the OAuth authorization callback URL be for generating a client id and secret?

Per [this comment](https://github.com/atmos/heaven/issues/6#issuecomment-36713749), it is OK for it to be blank.

**Comment by atmos** [comment]
Heroku does something on deploy where it writes out your database.yml file to your slug with your environmental information. We should probably just fixup the database.yml file up.

**Comment by atmos** [comment]
I'm not gonna be working on this project in the foreseeable future.
