### ISSUE TITLE
Heaven installation

### ISSUE THREAD

**Issue by mcapanema** [atmos/heaven#178]
Hello,
I am trying to install heaven, but, I came up with this doubt about the `Developer applications` that I must create to provide:
- `GITHUB_TOKEN`
- `GITHUB_CLIENT_ID`
- `GITHUB_CLIENT_SECRET`

Which `Authorization callback URL` should I provide to Github ?
Should this URL be valid or just a fake one to get the necessary information ?

**Comment by atmos** [comment]
I leave it empty.

**Comment by mcapanema** [comment]
Okay, now Github force you to provide some URL.
Since it has no effect over the configuration, I go with a fake one.
Thank you for your help.
