### ISSUE TITLE
Elastic Beanstalk doesn't work!

### ISSUE THREAD

**Issue by brodock** [atmos/heaven#179]
Check this deployment gist for a failed deployment example: https://gist.github.com/capybot/de8e08da4eb52270f409

After debugging and trying to understand how it gets the tarball, I found that, on heroku, curl will not create directories if it doesn't exists, so we must create `working_directory` before fetching source code.

The idea is to do a `FileUtils.mkdir_p(File.dirname(archive_path))` before this line: https://github.com/atmos/heaven/blob/003dd9e2ffa6637aaf2eb074b21791608b6c3e55/lib/heaven/provider/elastic_beanstalk.rb#L28

**Comment by brodock** [comment]
I've tried and updated the suggestion until I got the perfect fix... but it's just the first step.
Now, it's stuck a this step:

```
Beanstalk: Creating application: 
```

**Comment by atmos** [comment]
Hey, sorry. I haven't used the beanstalk app integration in a year or so. Keep looking, I hope it works out for ya.

**Comment by atmos** [comment]
I'm not gonna be working on this project in the foreseeable future.
