### ISSUE TITLE
A question on `github_authenticate`

### ISSUE THREAD

**Issue by willdurand** [atmos/heaven#187]
Hi @atmos, I am sorry to bother you since this issue is not entirely related to Heaven.

I am wondering how the `github_authenticate` method (used here: https://github.com/atmos/heaven/blob/master/config/routes.rb#L4-L6) should deal with assets?

I use a self-hosted version of Heaven, which works well except for the `resque-web` dashboard. All assets have to be double-checked by the GitHub OAuth dance, which does not (always) work well (I have to refresh the page several times to get the dashboard with the assets correctly loaded):

![screen shot 2016-03-21 at 12 58 36](https://cloud.githubusercontent.com/assets/217628/13918008/c1d3e986-ef64-11e5-9e92-77f510e9581a.png)

The other issue is that I am not really a Rails expert, so I may miss an obvious solution. In addition, "assets" are not served by the web server (nginx) since I don't know where resque's assets are located.

Thank you,
Will

**Comment by fakeatmos** [comment]
@willdurand So your best bet would be to have nginx/apache serve the static assets before it hits the rails process. Something like this, http://stackoverflow.com/questions/9929298/why-are-my-assets-not-served-through-a-reverse-proxy-in-apache

Your google keywords should be "nginx static asset rails reverse proxy." Let me know if you can't get past it with that.

**Comment by willdurand** [comment]
@atmos is @fakeatmos your evil twin?

**Comment by atmos** [comment]
I'm not gonna be working on this project in the foreseeable future.
