### ISSUE TITLE
How to host heaven on ubuntu14.04 instead of heroku

### ISSUE THREAD

**Issue by on99** [atmos/heaven#188]
This is quite important to self-host heaven as we do not want to introduce heroku.

**Comment by willdurand** [comment]
Heaven is a rails app, so I'd say it should be hosted "just" like any other Rails app. In addition, what you should do is define all the env variables required (see `app.json` + the documentation).

**Comment by on99** [comment]
@willdurand Yeh I agree with you. I hope there is an official document of installation on ubuntu14.04, for someone like me which has no enough knowledge in ruby.

**Comment by atmos** [comment]
There isn't currently. I've debated putting a docker container together. Would that help you?

**Comment by on99** [comment]
@atmos  Rails environment is not so easy to setup, docker container absolutely helps!

**Comment by gogames** [comment]
@atmos any update on it?

**Comment by atmos** [comment]
@gogames Sorry, not yet. I've been busy not working and have been focusing what little free time to have to something you no longer need to run yourself, https://github.com/atmos/slash-heroku .

**Comment by on99** [comment]
@atmos  👍 It took me a day to setup heaven on centos and now heroku app is deleted XD. Hope I have time to write a blog for it.

**Comment by atmos** [comment]
I'm not gonna be working on this project in the foreseeable future.
