### ISSUE TITLE
New payload for deployment statuses

### ISSUE THREAD

**Issue by willdurand** [atmos/heaven#189]
Hi!

GitHub gave some love to the Deployment API (https://developer.github.com/changes/2016-04-06-deployment-and-deployment-status-enhancements/) recently. There are a few interesting things, such as the `environment_url` field to access the application.

My question is: how would you see this feature implemented? I am wondering "who" is responsible for defining this value: should it be sent by `hubot-deploy` (or any other tool that sends deployment events with a (custom) payload), or should it be determined by Heaven?

As a `hubot-deploy` + `heaven` user with a "fixed" staging env, I would like to define the `environment_url` in the `apps.json` file, but it would mean having an array of URLs for each environment (or have `environment_<name>_url` params like for Heroku app name).

On the other hand, Heaven is not aware of the URLs of the apps it deploys.

**Comment by willdurand** [comment]
Hey! I have implemented the `environment_url` in https://github.com/TailorDev/heaven/pull/1/commits/d808e8dbb7b62ab51fbc1241f462b0e510b3d3eb. I put the following settings in my `apps.json` (pattern is: `<environment>_url`):

```
{
    ...,
    "production_url": "https://example.org",
    "staging_url": "https://staging.example.org"
```

**Comment by atmos** [comment]
Can you send me a PR for that? We finally moved to slack but are still using hubot-deploy for different adapters.

**Comment by willdurand** [comment]
My only concern right now is that I don't really know how to test this feature.. (otherwise I would have open a PR earlier ;-)). Any hint maybe?

**Comment by atmos** [comment]
Maybe add them to the payloads in the fixtures and verify the presence of the links for notifiers or at least verify they're retrievable via the instance methods on notifier?
