### ISSUE TITLE
DEPLOYMENT_PRIVATE_KEY doesn't get used

### ISSUE THREAD

**Issue by kevin1024** [atmos/heaven#192]
I'm running into a pretty strange problem where `DEPLOYMENT_PRIVATE_KEY` is not getting used in my heroku deploy of heaven master.

I believe I have tracked down the issue though.  Check this out:

https://github.com/atmos/heaven/blob/master/app/models/deployment/credentials.rb#L6

The ssh config and private key gets put in /tmp/some-crazy-hash/.ssh, and then the `$HOME` variable gets overridden.  That means when ssh goes to look for its config, it should look there.

However, on Heroku cedar-14 (OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.6, OpenSSL 1.0.1f 6 Jan 2014), ssh *does not look in the $HOME variable*!  It is using the home directory from /etc/passwd (/app) to find the ssh config, and does not find it there.

This is apparently normal behavior for openssh - see [this patch](http://lists.mindrot.org/pipermail/openssh-unix-dev/2001-March/005726.html) where they added a little notice in the README:

```
OpenSSH never uses $HOME to search for user config files but the
value in the pw_dir field in /etc/passwd.
```

**Comment by atmos** [comment]
I'm using it successfully on cedar but don't have anything using capistrano on cedar-14. I wonder what the difference is.

**Comment by kevin1024** [comment]
Heroku doesn't seem to be letting me provision an app on an older stack so I don't have a way of verifying that it's working on an older stack.

Not sure the best way to fix this.  I might just end up running off a fork that puts the credentials in the user's actual home directory (/app on heroku).  What was the original motivation for putting the credentials in a temp directory?  The only thing I have to go off of is [this comment](https://github.com/atmos/heaven/blob/master/app/models/deployment/credentials.rb#L6):

> This makes git and ssh work
> without worrying about impacting other deployment processes.

but I'm not sure what it means by "other deployment processes".

Happy to send a pull request to put the ssh config in the user's actual home directory instead of overriding the $HOME var.  Let me know!

**Comment by atmos** [comment]
I think my concern was multiple ssh accounts but reading from the env var sorta lends to one. Shoot me a PR and i'll see how well it works with my existing install.

**Comment by kevin1024** [comment]
Sounds good: #193
