### ISSUE TITLE
Question regarding Capistrano 3 support.

### ISSUE THREAD

**Issue by balbeko** [atmos/heaven#61]
Hey guys, to run `heaven` with `capistrano 3`  projects on my end i had to do this change HearstDigitalStudios/heaven@b60bc057230ec015e4d6ab721de33761c9eaabaf and change `capistrano` version in my Gemfile obviously. 
IIRC – capistrano2 is not sensitive to argument order, but capistrano3 is – so maybe it make sense to set an and order to `cap <env> <task> <additional args>` as a default behaviour, so it would make things easier for those like me, who use cap3 and willing to use heaven as well.

**Comment by acorncom** [comment]
Per https://github.com/atmos/heaven/pull/62#issuecomment-110494028, Capistrano 3 works well with this, so this issue should be able to be closed
