### ISSUE TITLE
no error logging when capistrano task can't clone the repo

### ISSUE THREAD

**Issue by tcrayford** [atmos/heaven#73]
if you give the github auth key incorrect permissions (and so cloning the repo 403s), then the gist output is empty, and there is no log anywhere of the error.

Two suggestions:
1) always log stdout/stderr to `Rails.logger` when a job fails (I can PR my code for this if you'd like)
2) This shouldn't result in no gist output. Entirely unsure why that's the case.

**Comment by dblandin** [comment]
I believe this should be resolved with #115.
