### ISSUE TITLE
Make auto-deploy configurable on some level

### ISSUE THREAD

**Issue by brentc** [atmos/heaven#82]
I see this was discussed in #45, but as that is now closed and I don't see another issue open for this, I'll open one....

We maintain a separate branch with auto-deploy functionality explicitly removed because we want to control when our production environment is updated (semi-continunuous-deployment, if you will). 

In testing some new functionality I'm working on for a PR, I forgot about that and was running heaven's master branch and whoops! Auto-deploy to production.

I would really appreciate some way to disable this functionality, or even better, change it to opt-in.

**Comment by atmos** [comment]
I'm not gonna be working on this project in the foreseeable future.
